name: tf-static-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-static-checks:
    uses: clouddrove/test-tfsec/.github/workflows/tf-static-checks.yml@master