name: tfsec
permissions: write-all
on:
  pull_request:
  workflow_dispatch:
jobs:
  call-workflow-tfsec:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec/
    secrets: inherit
    with:
      working_directory: '.' 
